crypto

In [1]:
from alpaca.data.historical import CryptoHistoricalDataClient
from alpaca.data.requests import CryptoBarsRequest
from alpaca.data.timeframe import TimeFrame
from datetime import datetime

# no keys required for crypto data
client = CryptoHistoricalDataClient()

request_params = CryptoBarsRequest(
                        symbol_or_symbols=["BTC/USD"],
                        timeframe=TimeFrame.Day,
                        start=datetime(2022, 7, 1),
                        end=datetime(2022, 9, 1)
                 )

bars = client.get_crypto_bars(request_params)

# convert to dataframe
bars.df

                                       open      high       low     close  \
symbol  timestamp
BTC/USD 2022-07-01 00:00:00+00:00  19935.53  20896.36  18940.00  19256.75
        2022-07-02 00:00:00+00:00  19261.58  19441.90  18956.79  19226.53
        2022-07-03 00:00:00+00:00  19227.69  19625.32  18752.98  19290.68
        2022-07-04 00:00:00+00:00  19292.88  20320.00  19034.13  20212.61
        2022-07-05 00:00:00+00:00  20212.61  20728.50  19281.37  20157.22
...                                     ...       ...       ...       ...
        2022-08-28 00:00:00+00:00  20038.74  20158.00  19520.19  19552.34
        2022-08-29 00:00:00+00:00  19555.69  20419.00  19544.89  20290.00
        2022-08-30 00:00:00+00:00  20289.97  20578.00  19541.13  19812.65
        2022-08-31 00:00:00+00:00  19812.65  20486.06  19801.13  20060.32
        2022-09-01 00:00:00+00:00  20051.81  20205.83  19564.86  20132.97

                                        volume  trade_count          vwap
symbol  timestamp
BTC/USD 2022-07-01 00:00:00+00:00  9747.183616     148392.0  19619.593190
        2022-07-02 00:00:00+00:00  3913.931431      66000.0  19214.413569
        2022-07-03 00:00:00+00:00  3275.136164      94793.0  19160.073904
        2022-07-04 00:00:00+00:00  6404.379456     213657.0  19653.972156
        2022-07-05 00:00:00+00:00  9137.287715     270041.0  19980.483912
...                                        ...          ...           ...
        2022-08-28 00:00:00+00:00  5250.261734      63389.0  19951.621498
        2022-08-29 00:00:00+00:00  7323.765069      91779.0  20000.535363
        2022-08-30 00:00:00+00:00  9641.439173     114320.0  20048.720103
        2022-08-31 00:00:00+00:00  7300.808548     105778.0  20187.103643
        2022-09-01 00:00:00+00:00  7529.674053     114052.0  19934.701556

[63 rows x 7 columns]

stocks

In [2]:
api_key='PKCGQ99MC5FQA1P8ZSRE'
secret_key='rkWLI1F2poiTbuERdzozfOLgVV6mrFKTH27Ugvb1'
from alpaca.data.historical.stock import StockHistoricalDataClient

# setup stock historical data client
stock_historical_data_client = StockHistoricalDataClient(api_key, secret_key)

from alpaca.data.requests import StockBarsRequest
from alpaca.data.timeframe import TimeFrame, TimeFrameUnit
import pendulum as dt
timez_zone="America/New_York"
current_time=dt.now(tz=timez_zone)
print(current_time)
req = StockBarsRequest(
    symbol_or_symbols = 'TSLA',
    timeframe=TimeFrame(amount = 1, unit = TimeFrameUnit.Hour), # specify timeframe
    start = current_time-dt.duration(days=30),                          # specify start datetime, default=the beginning of the current day.
    end_date=current_time#-dt.duration(days=10),                                        # specify end datetime, default=now
    # limit = 2,                                               # specify limit
)

history1=stock_historical_data_client.get_stock_bars(req).df
history1

2025-09-28 08:05:55.632236-04:00

                                      open      high       low     close  \
symbol timestamp
TSLA   2025-08-29 13:00:00+00:00  345.7000  348.7499  343.1500  343.4551
       2025-08-29 14:00:00+00:00  343.5300  344.5000  337.4800  338.1580
       2025-08-29 15:00:00+00:00  338.1300  339.6768  334.7800  335.6978
       2025-08-29 16:00:00+00:00  335.6375  336.9400  335.3000  335.5800
       2025-08-29 17:00:00+00:00  335.5600  335.5600  332.6500  333.5800
...                                    ...       ...       ...       ...
       2025-09-26 19:00:00+00:00  438.4150  440.4700  437.4261  440.4199
       2025-09-26 20:00:00+00:00  440.4065  440.6875  439.6500  439.9500
       2025-09-26 21:00:00+00:00  439.9507  440.0000  439.2263  439.6746
       2025-09-26 22:00:00+00:00  439.7900  440.4000  439.7900  440.0481
       2025-09-26 23:00:00+00:00  440.0100  440.1800  439.5500  440.0000

                                      volume  trade_count        vwap
symbol timestamp
TSLA   2025-08-29 13:00:00+00:00   9372014.0     133522.0  345.740020
       2025-08-29 14:00:00+00:00  16158875.0     243516.0  339.585595
       2025-08-29 15:00:00+00:00  11984515.0     168116.0  337.070124
       2025-08-29 16:00:00+00:00   6816183.0      95999.0  335.965882
       2025-08-29 17:00:00+00:00   8803943.0     126345.0  333.838647
...                                      ...          ...         ...
       2025-09-26 19:00:00+00:00  13670054.0     196900.0  438.905197
       2025-09-26 20:00:00+00:00   6913577.0      15679.0  440.367556
       2025-09-26 21:00:00+00:00    278741.0       6639.0  439.769764
       2025-09-26 22:00:00+00:00    149592.0       5485.0  440.180470
       2025-09-26 23:00:00+00:00    189248.0       4312.0  439.861074

[315 rows x 7 columns]