crypto

In [4]:
from alpaca.data.historical import CryptoHistoricalDataClient
from alpaca.data.requests import CryptoBarsRequest
from alpaca.data.timeframe import TimeFrame
from datetime import datetime

# no keys required for crypto data
client = CryptoHistoricalDataClient()

request_params = CryptoBarsRequest(
                        symbol_or_symbols=["BTC/USD"],
                        timeframe=TimeFrame.Hour,
                        start=datetime(2025, 1, 1),
                        end=datetime(2025, 2, 1)
                 )

bars = client.get_crypto_bars(request_params)

# convert to dataframe
bars.df

                                          open         high          low  \
symbol  timestamp
BTC/USD 2025-01-01 00:00:00+00:00   93381.5825   94314.6920   93296.6825
        2025-01-01 01:00:00+00:00   94176.1550   94176.1550   93405.4355
        2025-01-01 02:00:00+00:00   93469.8350   93875.0150   93469.8350
        2025-01-01 03:00:00+00:00   93800.5530   93855.0500   93560.1350
        2025-01-01 04:00:00+00:00   93582.9550   93609.2135   93319.7705
...                                        ...          ...          ...
        2025-01-31 20:00:00+00:00  102250.4000  102269.3000  101582.7700
        2025-01-31 21:00:00+00:00  101544.6690  102090.7000  101544.6690
        2025-01-31 22:00:00+00:00  102134.2950  102471.2400  101898.0000
        2025-01-31 23:00:00+00:00  102181.8350  102433.5300  101988.0045
        2025-02-01 00:00:00+00:00  102374.0980  102513.4850  102209.3250

                                         close    volume  trade_count  \
symbol  timestamp
BTC/USD 2025-01-01 00:00:00+00:00   94194.6800  0.000062          1.0
        2025-01-01 01:00:00+00:00   93405.4355  0.000000          0.0
        2025-01-01 02:00:00+00:00   93858.0560  0.005930          3.0
        2025-01-01 03:00:00+00:00   93641.1685  0.005000          1.0
        2025-01-01 04:00:00+00:00   93319.7705  0.011443          3.0
...                                        ...       ...          ...
        2025-01-31 20:00:00+00:00  101606.8345  0.835472        151.0
        2025-01-31 21:00:00+00:00  102090.7000  0.020838          8.0
        2025-01-31 22:00:00+00:00  102204.8000  0.057959          5.0
        2025-01-31 23:00:00+00:00  102408.0500  0.002496          3.0
        2025-02-01 00:00:00+00:00  102498.0590  0.000000          0.0

                                            vwap
symbol  timestamp
BTC/USD 2025-01-01 00:00:00+00:00   93451.940000
        2025-01-01 01:00:00+00:00   94144.957500
        2025-01-01 02:00:00+00:00   93732.454854
        2025-01-01 03:00:00+00:00   93829.600000
        2025-01-01 04:00:00+00:00   93540.704570
...                                          ...
        2025-01-31 20:00:00+00:00  101816.968613
        2025-01-31 21:00:00+00:00  101733.694723
        2025-01-31 22:00:00+00:00  102094.152625
        2025-01-31 23:00:00+00:00  102363.991874
        2025-02-01 00:00:00+00:00  102374.098000

[745 rows x 7 columns]

stocks

In [6]:
api_key='PKCGQ99MC5FQA1P8ZSRE'
secret_key='rkWLI1F2poiTbuERdzozfOLgVV6mrFKTH27Ugvb1'
from alpaca.data.historical.stock import StockHistoricalDataClient

# setup stock historical data client
stock_historical_data_client = StockHistoricalDataClient(api_key, secret_key)

from alpaca.data.requests import StockBarsRequest
from alpaca.data.timeframe import TimeFrame, TimeFrameUnit
import pendulum as dt
timez_zone="America/New_York"
current_time=dt.now(tz=timez_zone)
print(current_time)
req = StockBarsRequest(
    symbol_or_symbols = 'NVDA',
    timeframe=TimeFrame(amount = 1, unit = TimeFrameUnit.Hour), # specify timeframe
    start = current_time-dt.duration(days=30),                          # specify start datetime, default=the beginning of the current day.
    end_date=current_time#-dt.duration(days=10),                                        # specify end datetime, default=now
    # limit = 2,                                               # specify limit
)

history1=stock_historical_data_client.get_stock_bars(req).df
history1

2025-09-28 08:17:48.225052-04:00

                                      open      high       low     close  \
symbol timestamp
NVDA   2025-08-29 13:00:00+00:00  178.4100  178.6500  173.7600  174.7800
       2025-08-29 14:00:00+00:00  174.7900  175.4900  173.3700  173.6650
       2025-08-29 15:00:00+00:00  173.6500  175.1399  173.5100  173.7651
       2025-08-29 16:00:00+00:00  173.7700  174.7700  173.7200  174.4450
       2025-08-29 17:00:00+00:00  174.4450  174.4450  173.1450  174.0700
...                                    ...       ...       ...       ...
       2025-09-26 19:00:00+00:00  177.3800  179.7700  177.1800  178.1900
       2025-09-26 20:00:00+00:00  178.1900  178.3000  177.8634  177.9000
       2025-09-26 21:00:00+00:00  177.9000  177.9000  177.6201  177.6700
       2025-09-26 22:00:00+00:00  177.6224  177.7400  177.5201  177.6502
       2025-09-26 23:00:00+00:00  177.6500  177.7500  177.5500  177.6400

                                      volume  trade_count        vwap
symbol timestamp
NVDA   2025-08-29 13:00:00+00:00  50370537.0     554024.0  175.500652
       2025-08-29 14:00:00+00:00  45920914.0     563604.0  174.483499
       2025-08-29 15:00:00+00:00  28499325.0     314653.0  174.380464
       2025-08-29 16:00:00+00:00  16425217.0     184579.0  174.365375
       2025-08-29 17:00:00+00:00  22723025.0     241305.0  173.745577
...                                      ...          ...         ...
       2025-09-26 19:00:00+00:00  19603078.0     198271.0  177.739217
       2025-09-26 20:00:00+00:00  13270949.0       6759.0  178.185720
       2025-09-26 21:00:00+00:00    199400.0       3293.0  177.778850
       2025-09-26 22:00:00+00:00    106541.0       2527.0  177.650539
       2025-09-26 23:00:00+00:00    193490.0       2495.0  177.655192

[315 rows x 7 columns]