In [2]:
import yfinance as yf
data=yf.download("AAPL", period="5d", interval="15m",multi_level_index=False)
data

/var/folders/d_/rsnj8g2n4f362bxt3tz9n95w0000gn/T/ipykernel_96378/1119453906.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data=yf.download("AAPL", period="5d", interval="15m",multi_level_index=False)
[*********************100%***********************]  1 of 1 completed

,Close,High,Low,Open,Volume
Datetime,,,,,
2025-09-15 13:30:00+00:00,235.682495,238.190002,235.660004,237.000000,7824038
2025-09-15 13:45:00+00:00,235.359894,235.940002,235.029999,235.684998,2909603
2025-09-15 14:00:00+00:00,235.360001,235.669998,235.054993,235.339996,1686678
2025-09-15 14:15:00+00:00,236.214996,236.300003,235.253403,235.369995,1713898
2025-09-15 14:30:00+00:00,236.470001,236.619995,235.660004,236.210007,1454036
...,...,...,...,...,...
2025-09-19 18:45:00+00:00,245.509995,245.910004,245.190994,245.809998,1563834
2025-09-19 19:00:00+00:00,245.695007,245.789993,245.440994,245.500000,2284537
2025-09-19 19:15:00+00:00,245.610001,245.889999,245.470001,245.690308,2000545
2025-09-19 19:30:00+00:00,244.850006,245.936798,244.809998,245.600006,3170903
2025-09-19 19:45:00+00:00,245.289993,246.300003,244.740005,244.860001,9815625

In [7]:
t1=yf.Ticker('RELIANCE.NS')
i1=t1.info

In [8]:
i1.get('beta')

0.217